// Generated by IcedCoffeeScript 108.0.11
(function() {
  var CategoryFilter, rangeFilter;

  CategoryFilter = require('camshaft/lib/filter/category.js');

  rangeFilter = require('camshaft/lib/filter/range.js');

  module.exports = function(layer_sql, filters) {
    var column, filter, key, params, sql;
    if (!filters) {
      return layer_sql;
    }
    for (key in filters) {
      filter = filters[key];
      column = filter.column;
      params = filter.params;
      switch (filter.type) {
        case 'range':
          if (params.column_type === 'date') {
            column = "date_part('epoch', " + column + ")";
          }
          if (Number.isFinite(params.min) && Number.isFinite(params.max)) {
            sql = "select * from (" + layer_sql + ") patch_filter where " + column + " between " + params.min + " and " + params.max;
          } else if (Number.isFinite(params.min)) {
            sql = "select * from (" + layer_sql + ") patch_filter where " + column + " >= " + params.min;
          } else {
            sql = "select * from (" + layer_sql + ") patch_filter where " + column + " <= " + params.max;
          }
          break;
        case 'category':
          sql = new CategoryFilter(column, params).sql(layer_sql);
          break;
        default:
          sql = layer_sql;
      }
    }
    return sql;
  };

}).call(this);
